# Generated by Django 3.2.23 on 2024-02-28 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='nome',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='qtd_acertos',
            field=models.IntegerField(default=1, help_text='Pontuação necessária para passar %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='qtd_questoes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='tempo',
            field=models.IntegerField(default=1, help_text='Duração do teste em minutos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='topico',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='questao',
            name='formulario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formularios.formulario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='texto',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resposta',
            name='acerto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resposta',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='resposta',
            name='questao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formularios.questao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resposta',
            name='texto',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios.formulario')),
            ],
        ),
    ]
