# Generated by Django 3.2.23 on 2024-02-28 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_auto_20240228_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
