# Generated by Django 3.2.23 on 2024-03-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_auto_20240228_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='texto',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulario',
            name='qtd_acertos',
            field=models.IntegerField(help_text='Pontuação realizada pelo usuário %'),
        ),
    ]
