# Generated by Django 3.2.23 on 2024-03-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0004_auto_20240303_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='usuario',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
