# Generated by Django 3.2.23 on 2024-02-07 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
        ('empresas', '0004_auto_20240207_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='status_questionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='painel.status'),
        ),
    ]
