# Generated by Django 3.2.23 on 2024-02-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
        ('empresas', '0005_funcionario_status_questionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='funcao',
            field=models.CharField(choices=[('', '')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='status_questionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='painel.status'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='telefone',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
