# Generated by Django 3.2.23 on 2024-02-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_auto_20240207_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
